//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhongTroWebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HinhAnh
    {
        public int ID { get; set; }
        public byte[] Image { get; set; }
        public Nullable<int> ID_KhachHang { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public byte[] Image_Thumb { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
    }
}
