//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhongTroWebMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Phong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Phong()
        {
            this.HoaDons = new HashSet<HoaDon>();
            this.KhachHangs = new HashSet<KhachHang>();
        }
    
        public int ID { get; set; }

        [DisplayName("Tên phòng")]
        public string Name { get; set; }

        [DisplayName("Giá tiền")]
        public Nullable<int> GiaTien { get; set; }

        [DisplayName("Thuê")]
        public bool Thue { get; set; }

        [DisplayName("Ngày thuê")]
        public Nullable<System.DateTime> NgayThue { get; set; }

        [DisplayName("Chỉ số điện cũ")]
        public Nullable<int> ChiSoDienOld { get; set; }

        [DisplayName("Chỉ số điện mới")]
        public Nullable<int> ChiSoDien { get; set; }

        [DisplayName("Số NK nước")]
        public Nullable<int> SoNKNuoc { get; set; }

        [DisplayName("Chỉ số nước cũ")]
        public Nullable<int> ChiSoNuocOld { get; set; }

        [DisplayName("Chỉ số nước mới")]
        public Nullable<int> ChiSoNuoc { get; set; }

        [DisplayName("Ngày tạo")]
        public Nullable<System.DateTime> CreateDate { get; set; }

        [DisplayName("Ngày cập nhật")]
        public Nullable<System.DateTime> ModifyDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhachHang> KhachHangs { get; set; }
    }
}
