<?xml version="1.0" encoding="utf-8"?><Database Name="KTKS_DonKH" Class="DB_KTKS_DonKHDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=192.168.90.9;Initial Catalog=KTKS_DonKH;Persist Security Info=True;User ID=sa" SettingsObjectName="KTKS_DonKH.Properties.Settings" SettingsPropertyName="KTKS_DonKHConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ChiNhanh" Member="ChiNhanhs">
    <Type Name="ChiNhanh">
      <Column Name="MaCN" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenCN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="MaU" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TaiKhoan" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Login" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="User_DetailRole" Member="DetailRoles" ThisKey="MaU" OtherKey="MaU" Type="DetailRole" />
    </Type>
  </Table>
  <Table Name="dbo.ChungTu" Member="ChungTus">
    <Type Name="ChungTu">
      <Column Name="MaCT" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SoNKTong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoNKDaCap" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoNKCat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoNKNhan" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoNKConLai" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaLCT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="ChungTu_CTChungTu" Member="CTChungTus" ThisKey="MaCT" OtherKey="MaCT" Type="CTChungTu" />
      <Association Name="LoaiChungTu_ChungTu" Member="LoaiChungTu" ThisKey="MaLCT" OtherKey="MaLCT" Type="LoaiChungTu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChuyenDi" Member="ChuyenDis">
    <Type Name="ChuyenDi">
      <Column Name="STT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaChuyen" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NoiChuyenDi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="ChuyenDi_DCBD" Member="DCBDs" ThisKey="MaChuyen" OtherKey="MaChuyen" Type="DCBD" />
      <Association Name="ChuyenDi_DonKH" Member="DonKHs" ThisKey="MaChuyen" OtherKey="MaChuyen" Type="DonKH" />
      <Association Name="ChuyenDi_KTXM" Member="KTXMs" ThisKey="MaChuyen" OtherKey="MaChuyen" Type="KTXM" />
    </Type>
  </Table>
  <Table Name="dbo.CTChungTu" Member="CTChungTus">
    <Type Name="CTChungTu">
      <Column Name="DanhBo" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaCT" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoChinh" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SoNKDangKy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayHetHan" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="ChungTu_CTChungTu" Member="ChungTu" ThisKey="MaCT" OtherKey="MaCT" Type="ChungTu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DCBD" Member="DCBDs">
    <Type Name="DCBD">
      <Column Name="MaDCBD" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DCBD" Member="DCBD1" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MSThue" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GiaBieu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DinhMuc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SX" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="KD" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HCSN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NoiChuyenDen" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LyDoChuyenDen" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="KetQua" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Chuyen" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MaChuyen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LyDoChuyen" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Nhan" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MaDon" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="ChuyenDi_DCBD" Member="ChuyenDi" ThisKey="MaChuyen" OtherKey="MaChuyen" Type="ChuyenDi" IsForeignKey="true" />
      <Association Name="DonKH_DCBD" Member="DonKH" ThisKey="MaDon" OtherKey="MaDon" Type="DonKH" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DetailRoles" Member="DetailRoles">
    <Type Name="DetailRole">
      <Column Name="MaU" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaR" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CapQuyen" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="User_DetailRole" Member="User" ThisKey="MaU" OtherKey="MaU" Type="User" IsForeignKey="true" />
      <Association Name="Role_DetailRole" Member="Role" ThisKey="MaR" OtherKey="MaR" Type="Role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DonKH" Member="DonKHs">
    <Type Name="DonKH">
      <Column Name="MaDon" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DanhBo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HopDong" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MSThue" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GiaBieu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DinhMuc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SX" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HCSN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Dot" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ky" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Nam" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NoiDung" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="KiemTraDHN" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TienNuoc" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ChiSoNuoc" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DonGiaNuoc" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SangTen" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DangKyDM" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CatChuyenDM" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NuocDuc" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LoaiKhac" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LyDoLoaiKhac" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CT_HoaDon" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CT_HK_KT3" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CT_STT_GXNTT" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CT_HDTN_CQN" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CT_GC_SDSN" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CT_GXN2SN" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CT_GDKKD" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CT_GCNDTDHN" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DinhMucSau" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HieuLucTuKy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Chuyen" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MaChuyen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LyDoChuyen" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Nhan" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MaLD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="DonKH_DCBD" Member="DCBDs" ThisKey="MaDon" OtherKey="MaDon" Type="DCBD" />
      <Association Name="DonKH_KTXM" Member="KTXMs" ThisKey="MaDon" OtherKey="MaDon" Type="KTXM" />
      <Association Name="ChuyenDi_DonKH" Member="ChuyenDi" ThisKey="MaChuyen" OtherKey="MaChuyen" Type="ChuyenDi" IsForeignKey="true" />
      <Association Name="LoaiDon_DonKH" Member="LoaiDon" ThisKey="MaLD" OtherKey="MaLD" Type="LoaiDon" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KTXM" Member="KTXMs">
    <Type Name="KTXM">
      <Column Name="MaKTXM" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NoiChuyenDen" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LyDoChuyenDen" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="KetQua" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Chuyen" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MaChuyen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LyDoChuyen" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Nhan" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MaDon" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="ChuyenDi_KTXM" Member="ChuyenDi" ThisKey="MaChuyen" OtherKey="MaChuyen" Type="ChuyenDi" IsForeignKey="true" />
      <Association Name="DonKH_KTXM" Member="DonKH" ThisKey="MaDon" OtherKey="MaDon" Type="DonKH" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LichSuChungTu" Member="LichSuChungTus">
    <Type Name="LichSuChungTu">
      <Column Name="MaLSCT" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaCT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DanhBo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoNKTong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoNKDangKy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoNKConLai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoNKCat" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NhanNK_DiaChi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NhanNK_CN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NhanNK_DanhBo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoNKNhan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CatNK_DiaChi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CatNK_CN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CatNK_DanhBo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaDon" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiChungTu" Member="LoaiChungTus">
    <Type Name="LoaiChungTu">
      <Column Name="MaLCT" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="KyHieuLCT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TenLCT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ThoiHan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="LoaiChungTu_ChungTu" Member="ChungTus" ThisKey="MaLCT" OtherKey="MaLCT" Type="ChungTu" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiDon" Member="LoaiDons">
    <Type Name="LoaiDon">
      <Column Name="MaLD" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="KyHieuLD" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TenLD" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="LoaiDon_DonKH" Member="DonKHs" ThisKey="MaLD" OtherKey="MaLD" Type="DonKH" />
    </Type>
  </Table>
  <Table Name="dbo.Roles" Member="Roles">
    <Type Name="Role">
      <Column Name="MaR" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenR" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Role_DetailRole" Member="DetailRoles" ThisKey="MaR" OtherKey="MaR" Type="DetailRole" />
    </Type>
  </Table>
  <Table Name="dbo.TTKhachHang" Member="TTKhachHangs">
    <Type Name="TTKhachHang">
      <Column Name="Khu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Dot" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DanhBo" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CD" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CuLy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MSTLK" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GiaoUoc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DC1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DC2" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MSKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MSCQ" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GB" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HCSN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SX" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TGDM" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ky" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Nam" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CodeFu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CSCu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CSMoi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgayDSKT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgayDSKN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ChuKyDS" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LNCC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LNCT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LNBuToiThieu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LNSH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LNHCSN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LNSX" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LNDV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CuonGCS" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CuonSTT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GiaBan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ThueGTGT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PhiBVMT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TongCong" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GiaBanBuToiThieu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ThueGTGTBuToiThieu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PhiBVMTBuToiThieu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TongCongBuToiThieu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoPhatHanh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoHoaDon" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgayPhatHanh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Quan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Phuong" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoDHN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MSThue" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TileTieuThu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgayGanDHN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoHo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TTKhachHangDate" Member="TTKhachHangDates">
    <Type Name="TTKhachHangDate">
      <Column Name="Nam" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ky" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Dot" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>