#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIAYKHEN
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HOADON_TA")]
	public partial class GKDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertA_GIAYKHEN(A_GIAYKHEN instance);
    partial void UpdateA_GIAYKHEN(A_GIAYKHEN instance);
    partial void DeleteA_GIAYKHEN(A_GIAYKHEN instance);
    #endregion
		
		public GKDataContext() : 
				base(global::GIAYKHEN.Properties.Settings.Default.HOADON_TAConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public GKDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GKDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GKDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GKDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<A_GIAYKHEN> A_GIAYKHENs
		{
			get
			{
				return this.GetTable<A_GIAYKHEN>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.A_GIAYKHEN")]
	public partial class A_GIAYKHEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private bool _Name;
		
		private string _HOTEN;
		
		private string _HOTENB;
		
		private string _CHUCVU;
		
		private string _PHONGBAN;
		
		private bool _TAPTHE;
		
		private bool _CongDoan;
		
		private bool _DoanThanhNien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNameChanging(bool value);
    partial void OnNameChanged();
    partial void OnHOTENChanging(string value);
    partial void OnHOTENChanged();
    partial void OnHOTENBChanging(string value);
    partial void OnHOTENBChanged();
    partial void OnCHUCVUChanging(string value);
    partial void OnCHUCVUChanged();
    partial void OnPHONGBANChanging(string value);
    partial void OnPHONGBANChanged();
    partial void OnTAPTHEChanging(bool value);
    partial void OnTAPTHEChanged();
    partial void OnCongDoanChanging(bool value);
    partial void OnCongDoanChanged();
    partial void OnDoanThanhNienChanging(bool value);
    partial void OnDoanThanhNienChanged();
    #endregion
		
		public A_GIAYKHEN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="Bit NOT NULL")]
		public bool Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTEN", DbType="NVarChar(MAX)")]
		public string HOTEN
		{
			get
			{
				return this._HOTEN;
			}
			set
			{
				if ((this._HOTEN != value))
				{
					this.OnHOTENChanging(value);
					this.SendPropertyChanging();
					this._HOTEN = value;
					this.SendPropertyChanged("HOTEN");
					this.OnHOTENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTENB", DbType="NVarChar(200)")]
		public string HOTENB
		{
			get
			{
				return this._HOTENB;
			}
			set
			{
				if ((this._HOTENB != value))
				{
					this.OnHOTENBChanging(value);
					this.SendPropertyChanging();
					this._HOTENB = value;
					this.SendPropertyChanged("HOTENB");
					this.OnHOTENBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHUCVU", DbType="NVarChar(MAX)")]
		public string CHUCVU
		{
			get
			{
				return this._CHUCVU;
			}
			set
			{
				if ((this._CHUCVU != value))
				{
					this.OnCHUCVUChanging(value);
					this.SendPropertyChanging();
					this._CHUCVU = value;
					this.SendPropertyChanged("CHUCVU");
					this.OnCHUCVUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHONGBAN", DbType="NVarChar(MAX)")]
		public string PHONGBAN
		{
			get
			{
				return this._PHONGBAN;
			}
			set
			{
				if ((this._PHONGBAN != value))
				{
					this.OnPHONGBANChanging(value);
					this.SendPropertyChanging();
					this._PHONGBAN = value;
					this.SendPropertyChanged("PHONGBAN");
					this.OnPHONGBANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAPTHE", DbType="Bit NOT NULL")]
		public bool TAPTHE
		{
			get
			{
				return this._TAPTHE;
			}
			set
			{
				if ((this._TAPTHE != value))
				{
					this.OnTAPTHEChanging(value);
					this.SendPropertyChanging();
					this._TAPTHE = value;
					this.SendPropertyChanged("TAPTHE");
					this.OnTAPTHEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CongDoan", DbType="Bit NOT NULL")]
		public bool CongDoan
		{
			get
			{
				return this._CongDoan;
			}
			set
			{
				if ((this._CongDoan != value))
				{
					this.OnCongDoanChanging(value);
					this.SendPropertyChanging();
					this._CongDoan = value;
					this.SendPropertyChanged("CongDoan");
					this.OnCongDoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoanThanhNien", DbType="Bit NOT NULL")]
		public bool DoanThanhNien
		{
			get
			{
				return this._DoanThanhNien;
			}
			set
			{
				if ((this._DoanThanhNien != value))
				{
					this.OnDoanThanhNienChanging(value);
					this.SendPropertyChanging();
					this._DoanThanhNien = value;
					this.SendPropertyChanged("DoanThanhNien");
					this.OnDoanThanhNienChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
