<?xml version="1.0" encoding="utf-8"?><Database Name="KTKS_DonKH" Class="dbThuongVuDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=server9;Initial Catalog=KTKS_DonKH;Persist Security Info=True;User ID=sa" SettingsObjectName="DocSo_PC.Properties.Settings" SettingsPropertyName="KTKS_DonKHConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BanGiamDoc" Member="BanGiamDocs">
    <Type Name="BanGiamDoc">
      <Column Name="MaBGD" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ChucVu" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="KyTen" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="KyTenDuyet" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="An" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DonTu_ChiTiet" Member="DonTu_ChiTiets">
    <Type Name="DonTu_ChiTiet">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="STT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DanhBo" Type="System.String" DbType="Char(11)" CanBeNull="true" />
      <Column Name="MLT" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="HopDong" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="GiaBieu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DinhMuc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DinhMucHN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Dot" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ky" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Nam" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Quan" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="Phuong" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NguoiBao" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ChanHoaDon" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ChanHoaDon_Ngay" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ChanHoaDon_Ky" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ChanHoaDon_Nam" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaDon" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="HoanThanh" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="HoanThanh_Ngay" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="HoanThanh_GhiChu" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="DonTu_DonTu_ChiTiet" Member="DonTu" ThisKey="MaDon" OtherKey="MaDon" Type="DonTu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DonTu" Member="DonTus">
    <Type Name="DonTu">
      <Column Name="MaDon" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NamThang" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="STT" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="SoCongVan_PhongBanDoi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SoCongVan" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TongDB" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VanPhong" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="VanDeKhac" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="SoNK" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HieuLucKy" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="ThoiHan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgayHetHan" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DanhBo" Type="System.String" DbType="Char(11)" CanBeNull="true" />
      <Column Name="MLT" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="HopDong" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="GiaBieu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DinhMuc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Dot" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ky" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Nam" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Quan" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="Phuong" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgayHenGiaiQuyet" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ID_NhomDon" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Name_NhomDon" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ID_NhomDon_ChiTiet" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name_NhomDon_ChiTiet" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ID_NhomDon_PKH" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Name_NhomDon_PKH" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CT_HoaDon" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CT_GiayBao" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CT_HK_KT3" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CT_STT_GXNTT" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CT_HDTN_CQN" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CT_CQN" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CT_GC_SDSN" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CT_GXN2SN" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CT_GDKKD" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CT_GCNDTDHN" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CT_Khac" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CT_Khac_GhiChu" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="CT_HoNgheo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CT_HopDongNganHang" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CT_GiaiQuyet_Huy_DKCT" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CT_GiayUyQuyen" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MaPhong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="HoanThanh" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="HoanThanh_Ngay" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="HoanThanh_GhiChu" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="DonTu_DonTu_ChiTiet" Member="DonTu_ChiTiets" ThisKey="MaDon" OtherKey="MaDon" Type="DonTu_ChiTiet" />
    </Type>
  </Table>
</Database>