<?xml version="1.0" encoding="utf-8"?><Database Name="HOADON_TA" Class="dbThuTienDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=HOADON_TA;User ID=sa" SettingsObjectName="ThuTien.Properties.Settings" SettingsPropertyName="HOADON_TAConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TT_Menu" Member="TT_Menus">
    <Type Name="TT_Menu">
      <Column Name="MaMenu" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="STT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenMenu" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TextMenu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TenMenuCha" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TextMenuCha" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TT_Menu_TT_PhanQuyenNguoiDung" Member="TT_PhanQuyenNguoiDungs" ThisKey="MaMenu" OtherKey="MaMenu" Type="TT_PhanQuyenNguoiDung" />
      <Association Name="TT_Menu_TT_PhanQuyenNhom" Member="TT_PhanQuyenNhoms" ThisKey="MaMenu" OtherKey="MaMenu" Type="TT_PhanQuyenNhom" />
    </Type>
  </Table>
  <Table Name="dbo.TT_To" Member="TT_Tos">
    <Type Name="TT_To">
      <Column Name="MaTo" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenTo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TT_To_TT_NguoiDung" Member="TT_NguoiDungs" ThisKey="MaTo" OtherKey="MaTo" Type="TT_NguoiDung" />
    </Type>
  </Table>
  <Table Name="dbo.TT_NguoiDung" Member="TT_NguoiDungs">
    <Type Name="TT_NguoiDung">
      <Column Name="MaND" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TaiKhoan" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LoginDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MaTo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNhom" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TT_NguoiDung_TT_PhanQuyenNguoiDung" Member="TT_PhanQuyenNguoiDungs" ThisKey="MaND" OtherKey="MaND" Type="TT_PhanQuyenNguoiDung" />
      <Association Name="TT_To_TT_NguoiDung" Member="TT_To" ThisKey="MaTo" OtherKey="MaTo" Type="TT_To" IsForeignKey="true" />
      <Association Name="TT_Nhom_TT_NguoiDung" Member="TT_Nhom" ThisKey="MaNhom" OtherKey="MaNhom" Type="TT_Nhom" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TT_Nhom" Member="TT_Nhoms">
    <Type Name="TT_Nhom">
      <Column Name="MaNhom" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNhom" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TT_Nhom_TT_NguoiDung" Member="TT_NguoiDungs" ThisKey="MaNhom" OtherKey="MaNhom" Type="TT_NguoiDung" />
      <Association Name="TT_Nhom_TT_PhanQuyenNhom" Member="TT_PhanQuyenNhoms" ThisKey="MaNhom" OtherKey="MaNhom" Type="TT_PhanQuyenNhom" />
    </Type>
  </Table>
  <Table Name="dbo.TT_PhanQuyenNguoiDung" Member="TT_PhanQuyenNguoiDungs">
    <Type Name="TT_PhanQuyenNguoiDung">
      <Column Name="MaMenu" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaND" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ToanQuyen" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Xem" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Them" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Xoa" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Sua" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TT_Menu_TT_PhanQuyenNguoiDung" Member="TT_Menu" ThisKey="MaMenu" OtherKey="MaMenu" Type="TT_Menu" IsForeignKey="true" />
      <Association Name="TT_NguoiDung_TT_PhanQuyenNguoiDung" Member="TT_NguoiDung" ThisKey="MaND" OtherKey="MaND" Type="TT_NguoiDung" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TT_PhanQuyenNhom" Member="TT_PhanQuyenNhoms">
    <Type Name="TT_PhanQuyenNhom">
      <Column Name="MaMenu" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaNhom" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ToanQuyen" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Xem" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Them" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Xoa" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Sua" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TT_Menu_TT_PhanQuyenNhom" Member="TT_Menu" ThisKey="MaMenu" OtherKey="MaMenu" Type="TT_Menu" IsForeignKey="true" />
      <Association Name="TT_Nhom_TT_PhanQuyenNhom" Member="TT_Nhom" ThisKey="MaNhom" OtherKey="MaNhom" Type="TT_Nhom" IsForeignKey="true" />
    </Type>
  </Table>
</Database>