with t1 as
(
	SELECT t1.DHN_DANHBO,HCT_SOTHANGAN
	FROM [CAPNUOCTANHOA].[dbo].[TB_THAYDHN] t1
	join (select DHN_DANHBO,max(HCT_NGAYGAN) HCT_NGAYGAN from TB_THAYDHN where HCT_NGAYGAN is not null and hct_trongai <> 1 group by DHN_DANHBO) t2 on t1.DHN_DANHBO = t2.DHN_DANHBO and t1.HCT_NGAYGAN = t2.HCT_NGAYGAN and HCT_SOTHANGAN is not null
)
select DANHBO, SOTHANDH, HCT_SOTHANGAN
from TB_DULIEUKHACHHANG t2 join t1 on t2.DANHBO = t1.DHN_DANHBO and SOTHANDH <> HCT_SOTHANGAN


with t1 as
(
	SELECT t1.DHN_DANHBO,HCT_SOTHANGAN,t1.DHN_SOTHAN,t1.HCT_HIEUDHNGAN,t1.HCT_NGAYGAN,t1.HCT_CREATEBY,t1.HCT_MODIFYBY,t1.HCT_CREATEDATE,t1.HCT_MODIFYDATE
	FROM [CAPNUOCTANHOA].[dbo].[TB_THAYDHN] t1
	join (select DHN_DANHBO,max(HCT_NGAYGAN) HCT_NGAYGAN from TB_THAYDHN where HCT_NGAYGAN is not null and hct_trongai <> 1 group by DHN_DANHBO) t2 on t1.DHN_DANHBO = t2.DHN_DANHBO and t1.HCT_NGAYGAN = t2.HCT_NGAYGAN and HCT_SOTHANGAN is not null
)
select DANHBO, SOTHANDH, HCT_SOTHANGAN,t1.*,t2.MODIFYDATE,t2.MODIFYBY
from TB_DULIEUKHACHHANG t2 join t1 on t2.DANHBO = t1.DHN_DANHBO and SOTHANDH <> HCT_SOTHANGAN
where DANHBO in (select DanhBo  from sDHN.dbo.sDHN_TCT) and t1.HCT_HIEUDHNGAN iN ('SENSUS','DIEHL','EMS','B-METERS') and year(t1.HCT_NGAYGAN)>2019
order by t1.HCT_NGAYGAN