<?xml version="1.0" encoding="utf-8"?><Database Name="HOADON_TA" Class="dbThuTienDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=server9;Initial Catalog=HOADON_TA;Persist Security Info=True;User ID=tanhoa" SettingsObjectName="ThuTien.Properties.Settings" SettingsPropertyName="HOADON_TAConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TT_LichSuGiaoHD" Member="TT_LichSuGiaoHDs">
    <Type Name="TT_LichSuGiaoHD">
      <Column Name="MaHD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNV" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayGiaiTrach" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TT_Menu" Member="TT_Menus">
    <Type Name="TT_Menu">
      <Column Name="MaMenu" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="STT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenMenu" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TextMenu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TenMenuCha" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TextMenuCha" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TT_Menu_TT_PhanQuyenNguoiDung" Member="TT_PhanQuyenNguoiDungs" ThisKey="MaMenu" OtherKey="MaMenu" Type="TT_PhanQuyenNguoiDung" />
      <Association Name="TT_Menu_TT_PhanQuyenNhom" Member="TT_PhanQuyenNhoms" ThisKey="MaMenu" OtherKey="MaMenu" Type="TT_PhanQuyenNhom" />
    </Type>
  </Table>
  <Table Name="dbo.TT_Nhom" Member="TT_Nhoms">
    <Type Name="TT_Nhom">
      <Column Name="MaNhom" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNhom" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TT_Nhom_TT_PhanQuyenNhom" Member="TT_PhanQuyenNhoms" ThisKey="MaNhom" OtherKey="MaNhom" Type="TT_PhanQuyenNhom" />
      <Association Name="TT_Nhom_TT_NguoiDung" Member="TT_NguoiDungs" ThisKey="MaNhom" OtherKey="MaNhom" Type="TT_NguoiDung" />
    </Type>
  </Table>
  <Table Name="dbo.TT_PhanQuyenNguoiDung" Member="TT_PhanQuyenNguoiDungs">
    <Type Name="TT_PhanQuyenNguoiDung">
      <Column Name="MaMenu" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaND" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ToanQuyen" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Xem" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Them" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Xoa" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Sua" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="QuanLy" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TT_Menu_TT_PhanQuyenNguoiDung" Member="TT_Menu" ThisKey="MaMenu" OtherKey="MaMenu" Type="TT_Menu" IsForeignKey="true" />
      <Association Name="TT_NguoiDung_TT_PhanQuyenNguoiDung" Member="TT_NguoiDung" ThisKey="MaND" OtherKey="MaND" Type="TT_NguoiDung" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TT_PhanQuyenNhom" Member="TT_PhanQuyenNhoms">
    <Type Name="TT_PhanQuyenNhom">
      <Column Name="MaMenu" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaNhom" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ToanQuyen" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Xem" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Them" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Sua" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Xoa" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="QuanLy" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TT_Menu_TT_PhanQuyenNhom" Member="TT_Menu" ThisKey="MaMenu" OtherKey="MaMenu" Type="TT_Menu" IsForeignKey="true" />
      <Association Name="TT_Nhom_TT_PhanQuyenNhom" Member="TT_Nhom" ThisKey="MaNhom" OtherKey="MaNhom" Type="TT_Nhom" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TT_ThongTinDanhBo" Member="TT_ThongTinDanhBos">
    <Type Name="TT_ThongTinDanhBo">
      <Column Name="DanhBo" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DongNuoc" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NgayDN" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MoNuoc" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NgayMN" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SoTien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TT_HoaDonTon" Member="TT_HoaDonTons">
    <Type Name="TT_HoaDonTon">
      <Column Name="ID_HOADON" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DOT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DANHBA" Type="System.String" DbType="NVarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="HOPDONG" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="DUONG" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="GB" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TILESH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TILEHCSN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TILESX" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TILEDV" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DM" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CODE" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="CSCU" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CSMOI" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="SONGAY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TIEUTHU" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TIEUTHUBU" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TIEUTHUSH" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TIEUTHUSX" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TIEUTHUHCSN" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TIEUTHUDV" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="GIABAN" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="THUE" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="PHI" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TONGCONG" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="GIABAN_BU" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="THUE_BU" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="PHI_BU" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TONGCONG_BU" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="SOPHATHANH" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="SOHOADON" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="KY" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MA_NHANVIEN" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="NGAYGIAO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MST" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="NGAYGIAITRACH" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TUNGAY" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DENNGAY" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NAM" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MAY" Type="System.String" DbType="NChar(2)" CanBeNull="true" />
      <Column Name="STT" Type="System.String" DbType="NChar(5)" CanBeNull="true" />
      <Column Name="MALOTRINH" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Pol" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Column Name="TENKH" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="SO" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="DaXuLy" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TT_DangKyHD0" Member="TT_DangKyHD0s">
    <Type Name="TT_DangKyHD0">
      <Column Name="DanhBo" Type="System.String" DbType="VarChar(11) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaNV" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TT_TTCH" Member="TT_TTCHes">
    <Type Name="TT_TTCH">
      <Column Name="MaTTCH" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TT_TTCH_TT_CTTTCH" Member="TT_CTTTCHes" ThisKey="MaTTCH" OtherKey="MaTTCH" Type="TT_CTTTCH" />
    </Type>
  </Table>
  <Table Name="dbo.TT_CTTTCH" Member="TT_CTTTCHes">
    <Type Name="TT_CTTTCH">
      <Column Name="MaTTCH" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DanhBo" Type="System.String" DbType="VarChar(11) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CoDHN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ky" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TongCong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TieuThu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TT_TTCH_TT_CTTTCH" Member="TT_TTCH" ThisKey="MaTTCH" OtherKey="MaTTCH" Type="TT_TTCH" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ViewGetNamHD" Member="ViewGetNamHDs">
    <Type Name="ViewGetNamHD">
      <Column Name="NAM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TT_TraGop" Member="TT_TraGops">
    <Type Name="TT_TraGop">
      <Column Name="MaTG" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaHD" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoHoaDon" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="SoTien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayTra" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DaThanhToan" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SoPhieu" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TT_ChamCong" Member="TT_ChamCongs">
    <Type Name="TT_ChamCong">
      <Column Name="MaCC" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Thang" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nam" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TT_ChamCong_TT_CTChamCong" Member="TT_CTChamCongs" ThisKey="MaCC" OtherKey="MaCC" Type="TT_CTChamCong" />
    </Type>
  </Table>
  <Table Name="dbo.TT_DuLieuKhachHang_DanhBo" Member="TT_DuLieuKhachHang_DanhBos">
    <Type Name="TT_DuLieuKhachHang_DanhBo">
      <Column Name="DanhBo" Type="System.String" DbType="VarChar(11) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SoTaiKhoan" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TT_CacLoaiPhi" Member="TT_CacLoaiPhis">
    <Type Name="TT_CacLoaiPhi">
      <Column Name="PhiMoNuoc" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TT_CTChamCong" Member="TT_CTChamCongs">
    <Type Name="TT_CTChamCong">
      <Column Name="MaCC" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaND" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="N1" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N2" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N3" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N4" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N5" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N6" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N7" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N8" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N9" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N10" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N11" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N12" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N13" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N14" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N15" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N16" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N17" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N18" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N19" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N20" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N21" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N22" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N23" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N24" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N25" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N26" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N27" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N28" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N29" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N30" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="N31" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="XS" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="KK" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TT_ChamCong_TT_CTChamCong" Member="TT_ChamCong" ThisKey="MaCC" OtherKey="MaCC" Type="TT_ChamCong" IsForeignKey="true" />
      <Association Name="TT_NguoiDung_TT_CTChamCong" Member="TT_NguoiDung" ThisKey="MaND" OtherKey="MaND" Type="TT_NguoiDung" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TT_VanTu" Member="TT_VanTus">
    <Type Name="TT_VanTu">
      <Column Name="DanhBo" Type="System.String" DbType="VarChar(11) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TT_TestHoaDonTon" Member="TT_TestHoaDonTons">
    <Type Name="TT_TestHoaDonTon">
      <Column Name="MaHD" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DanhBo" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="Nam" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ky" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Loai" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="SoPhatHanh" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="TieuThu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GiaBan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThueGTGT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PhiBVMT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MLT" Type="System.String" DbType="VarChar(9)" CanBeNull="true" />
      <Column Name="SoHoaDon" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="HoTen" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="SoNha" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Duong" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Xoa" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TT_XacNhanNo" Member="TT_XacNhanNos">
    <Type Name="TT_XacNhanNo">
      <Column Name="SoPhieu" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DanhBo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MLT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GiaBieu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DinhMuc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ky" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TongCong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TinhDenKy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Cat" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ViewGetDichVuThu" Member="ViewGetDichVuThus">
    <Type Name="ViewGetDichVuThu">
      <Column Name="ID" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TenDichVu" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TT_ThongTinKhachHang" Member="TT_ThongTinKhachHangs">
    <Type Name="TT_ThongTinKhachHang">
      <Column Name="DanhBo" Type="System.String" DbType="VarChar(11) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DienThoai" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TAMTHU" Member="TAMTHUs">
    <Type Name="TAMTHU">
      <Column Name="ID_TAMTHU" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DANHBA" Type="System.String" DbType="NChar(11)" CanBeNull="true" />
      <Column Name="FK_HOADON" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGAYTAMTHU" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MA_NHANVIEN_LUU" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="SoHoaDon" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SoPhieu" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="ChuyenKhoan" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MaNH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Xoa" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TienDu" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Tra" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NgayTra" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GhiChuTra" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TT_BangKe" Member="TT_BangKes">
    <Type Name="TT_BangKe">
      <Column Name="MaBK" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DanhBo" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="SoTien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Phi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateDate2" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TT_CongVan" Member="TT_CongVans">
    <Type Name="TT_CongVan">
      <Column Name="MaCV" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DanhBo" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="Loai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NoiDung" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TT_To" Member="TT_Tos">
    <Type Name="TT_To">
      <Column Name="MaTo" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenTo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HanhThu" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TuCuonGCS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DenCuonGCS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TT_To_TT_NguoiDung" Member="TT_NguoiDungs" ThisKey="MaTo" OtherKey="MaTo" Type="TT_NguoiDung" />
    </Type>
  </Table>
  <Table Name="dbo.TT_LichSuDieuChinhHD" Member="TT_LichSuDieuChinhHDs">
    <Type Name="TT_LichSuDieuChinhHD">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PHIEU_DC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGAY_VB" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FK_HOADON" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GIABAN_DC" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="THUE_DC" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="PHI_DC" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TONGCONG_DC" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="GB_DC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DM_DC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TIEUTHU_DC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGAY_DC" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GIABAN_BD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="THUE_BD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="PHI_BD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TONGCONG_BD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TIEUTHU_BD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TXL" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="GiaBieu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DinhMuc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TangGiam" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoHoaDon" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="SoPhieu" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="GIABAN_END" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="THUE_END" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="PHI_END" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TONGCONG_END" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TT_CTChuyenNoKhoDoi" Member="TT_CTChuyenNoKhoDois">
    <Type Name="TT_CTChuyenNoKhoDoi">
      <Column Name="MaHD" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoHoaDon" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="MaCNKD" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TT_ChuyenNoKhoDoi_TT_CTChuyenNoKhoDoi" Member="TT_ChuyenNoKhoDoi" ThisKey="MaCNKD" OtherKey="MaCNKD" Type="TT_ChuyenNoKhoDoi" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TT_CTDongNuoc" Member="TT_CTDongNuocs">
    <Type Name="TT_CTDongNuoc">
      <Column Name="MaDN" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaHD" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoHoaDon" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Ky" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TieuThu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GiaBan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThueGTGT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PhiBVMT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TongCong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TT_DongNuoc_TT_CTDongNuoc" Member="TT_DongNuoc" ThisKey="MaDN" OtherKey="MaDN" Type="TT_DongNuoc" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TT_LenhHuy" Member="TT_LenhHuys">
    <Type Name="TT_LenhHuy">
      <Column Name="MaHD" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoHoaDon" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="TinhTrang" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Cat" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TT_DuLieuKhachHang_SoHoaDon" Member="TT_DuLieuKhachHang_SoHoaDons">
    <Type Name="TT_DuLieuKhachHang_SoHoaDon">
      <Column Name="MaHD" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoHoaDon" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Tra" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TT_QuetGiaoTon" Member="TT_QuetGiaoTons">
    <Type Name="TT_QuetGiaoTon">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaHD" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoHoaDon" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TT_TienDu" Member="TT_TienDus">
    <Type Name="TT_TienDu">
      <Column Name="DanhBo" Type="System.String" DbType="VarChar(11) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoTien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Phi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ChoXuLy" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MaNH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TT_GiaBanBinhQuan" Member="TT_GiaBanBinhQuans">
    <Type Name="TT_GiaBanBinhQuan">
      <Column Name="Nam" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Ky" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TongGiaBan" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TongTieuThu" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="GiaBanBinhQuan" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TT_PhiMoNuocDoi" Member="TT_PhiMoNuocDois">
    <Type Name="TT_PhiMoNuocDoi">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DanhBo" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TT_TienDuQuay" Member="TT_TienDuQuays">
    <Type Name="TT_TienDuQuay">
      <Column Name="DanhBo" Type="System.String" DbType="VarChar(11) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoTien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Phi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ChoXuLy" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MaNH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TT_ChuyenNoKhoDoi" Member="TT_ChuyenNoKhoDois">
    <Type Name="TT_ChuyenNoKhoDoi">
      <Column Name="MaCNKD" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoPhieuYCCHDB" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NgayYCCHDB" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LyDo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DanhBo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TT_ChuyenNoKhoDoi_TT_CTChuyenNoKhoDoi" Member="TT_CTChuyenNoKhoDois" ThisKey="MaCNKD" OtherKey="MaCNKD" Type="TT_CTChuyenNoKhoDoi" />
    </Type>
  </Table>
  <Table Name="dbo.TT_TienDuLichSuQuay" Member="TT_TienDuLichSuQuays">
    <Type Name="TT_TienDuLichSuQuay">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DanhBo" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="SoTien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Loai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DanhBoChuyenNhan" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="MaHD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateDate2" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MaBK" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoHoaDon" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TT_TienDuLichSu" Member="TT_TienDuLichSus">
    <Type Name="TT_TienDuLichSu">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DanhBo" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="SoTien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Loai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DanhBoChuyenNhan" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="MaHD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateDate2" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MaBK" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoHoaDon" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TT_ToTrinhCatHuy" Member="TT_ToTrinhCatHuys">
    <Type Name="TT_ToTrinhCatHuy">
      <Column Name="MaTT" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Khoa" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DaKy" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TT_ToTrinhCatHuy_TT_CTToTrinhCatHuy" Member="TT_CTToTrinhCatHuys" ThisKey="MaTT" OtherKey="MaTT" Type="TT_CTToTrinhCatHuy" />
    </Type>
  </Table>
  <Table Name="dbo.TT_CTToTrinhCatHuy" Member="TT_CTToTrinhCatHuys">
    <Type Name="TT_CTToTrinhCatHuy">
      <Column Name="MaCTTT" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DanhBo" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="MLT" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="CoDHN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Ky" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="TongCong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TieuThu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MaHD" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="SoHoaDon" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="MaTT" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TT_ToTrinhCatHuy_TT_CTToTrinhCatHuy" Member="TT_ToTrinhCatHuy" ThisKey="MaTT" OtherKey="MaTT" Type="TT_ToTrinhCatHuy" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TT_CTTongHopNo" Member="TT_CTTongHopNos">
    <Type Name="TT_CTTongHopNo">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DanhBo" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Ky" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GiaBieu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DinhMuc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TieuThu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GiaBan" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="ThueGTGT" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="PhiBVMT" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TongCong" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TienDu" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MaTHN" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TT_TongHopNo_TT_CTTongHopNo" Member="TT_TongHopNo" ThisKey="MaTHN" OtherKey="MaTHN" Type="TT_TongHopNo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TT_DangKyKiemTra" Member="TT_DangKyKiemTras">
    <Type Name="TT_DangKyKiemTra">
      <Column Name="MaDKKT" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TT_DangKyKiemTra_TT_CTDangKyKiemTra" Member="TT_CTDangKyKiemTras" ThisKey="MaDKKT" OtherKey="MaDKKT" Type="TT_CTDangKyKiemTra" />
    </Type>
  </Table>
  <Table Name="dbo.TT_CTDangKyKiemTra" Member="TT_CTDangKyKiemTras">
    <Type Name="TT_CTDangKyKiemTra">
      <Column Name="MaCTDKKT" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DanhBo" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="MaNV_HanhThu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HanhThu" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="MLT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="GB_DM_Cu" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NoiDung" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NgayNhan" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MaDKKT" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TT_DangKyKiemTra_TT_CTDangKyKiemTra" Member="TT_DangKyKiemTra" ThisKey="MaDKKT" OtherKey="MaDKKT" Type="TT_DangKyKiemTra" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TT_DangKy" Member="TT_DangKies">
    <Type Name="TT_DangKy">
      <Column Name="DanhBo" Type="System.String" DbType="VarChar(11) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaNV" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.NGANHANG" Member="NGANHANGs">
    <Type Name="NGANHANG">
      <Column Name="ID_NGANHANG" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="KyHieu" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NGANHANG" Member="NGANHANG1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoTK" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TT_PhiMoNuoc" Member="TT_PhiMoNuocs">
    <Type Name="TT_PhiMoNuoc">
      <Column Name="MaPMN" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DanhBo" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NgayBK" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SoTien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TongCong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PhiMoNuoc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoTK" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NhanHD" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NgayNhanHD" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TraHD" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NgayTraHD" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MaKQDN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TT_NguoiDung" Member="TT_NguoiDungs">
    <Type Name="TT_NguoiDung">
      <Column Name="MaND" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="STT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TaiKhoan" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LoginDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NamVaoLam" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayPhepNamCu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayPhepNamMoi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TongNgayPhep" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Admin" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PhoGiamDoc" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Doi" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ToTruong" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="HanhThu" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DongNuoc" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="VanPhong" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ChamCong" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="An" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MaTo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNhom" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UID" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TT_NguoiDung_TT_PhanQuyenNguoiDung" Member="TT_PhanQuyenNguoiDungs" ThisKey="MaND" OtherKey="MaND" Type="TT_PhanQuyenNguoiDung" />
      <Association Name="TT_NguoiDung_TT_CTChamCong" Member="TT_CTChamCongs" ThisKey="MaND" OtherKey="MaND" Type="TT_CTChamCong" />
      <Association Name="TT_Nhom_TT_NguoiDung" Member="TT_Nhom" ThisKey="MaNhom" OtherKey="MaNhom" Type="TT_Nhom" IsForeignKey="true" />
      <Association Name="TT_To_TT_NguoiDung" Member="TT_To" ThisKey="MaTo" OtherKey="MaTo" Type="TT_To" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TT_GiaoHDDienThoai" Member="TT_GiaoHDDienThoais">
    <Type Name="TT_GiaoHDDienThoai">
      <Column Name="MaHD" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoHoaDon" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MaNV" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NgayDi" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TT_KQDongNuoc" Member="TT_KQDongNuocs">
    <Type Name="TT_KQDongNuoc">
      <Column Name="MaKQDN" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DanhBo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HopDong" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MLT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DongNuoc" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="HinhDN" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="NgayDN" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayDN_ThucTe" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Hieu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Co" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoThan" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ChiSoDN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ChiMatSo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ChiKhoaGoc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LyDo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PhiMoNuoc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KhongThuPhi" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PhiMoNuocKhongThu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DongNuoc2" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="HinhDN1" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="NgayDN1" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayDN1_ThucTe" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ChiSoDN1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DongPhi" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ChuyenKhoan" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NgayDongPhi" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SoPhieuDN" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NgaySoPhieuDN" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ChuyenDN" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NgayChuyenDN" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SoPhieuDN1" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NgaySoPhieuDN1" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ChuyenDN1" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NgayChuyenDN1" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TroNgaiMN" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MoNuoc" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="HinhMN" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="NgayMN" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayMN_ThucTe" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ChiSoMN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GhiChuMN" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="SoPhieuMN" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NgaySoPhieuMN" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ChuyenMN" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NgayChuyenMN" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GhiChuTroNgai" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MaDN" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="DaKy" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NgayKy" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TT_DongNuoc_TT_KQDongNuoc" Member="TT_DongNuoc" ThisKey="MaDN" OtherKey="MaDN" Type="TT_DongNuoc" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HOADON" Member="HOADONs">
    <Type Name="HOADON">
      <Column Name="ID_HOADON" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DOT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DANHBA" Type="System.String" DbType="NVarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="HOPDONG" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="DUONG" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="GB" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TILESH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TILEHCSN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TILESX" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TILEDV" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DM" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CODE" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="CSCU" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CSMOI" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="SONGAY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TIEUTHU" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TIEUTHUBU" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TIEUTHUSH" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TIEUTHUSX" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TIEUTHUHCSN" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TIEUTHUDV" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="GIABAN" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="THUE" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="PHI" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TONGCONG" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="GIABAN_BU" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="THUE_BU" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="PHI_BU" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TONGCONG_BU" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="SOPHATHANH" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="SOHOADON" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="KY" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NGAYGIAO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MST" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="NGAYGIAITRACH" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TUNGAY" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DENNGAY" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NAM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MAY" Type="System.String" DbType="NChar(2)" CanBeNull="true" />
      <Column Name="STT" Type="System.String" DbType="NChar(5)" CanBeNull="true" />
      <Column Name="MALOTRINH" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="DOTCHIA" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="NGAYGIAOTON" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TENKH" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="SO" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="MaNV_HanhThu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNV_GiaoTon" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNV_HanhThuTruoc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DangNgan_HanhThu" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DangNgan_Quay" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DangNgan_ChuyenKhoan" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DangNgan_Ton" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MaNV_DangNgan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Thu2Lan" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Thu2Lan_ChuyenKhoan" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Thu2Lan_Tra" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Thu2Lan_NgayTra" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Thu2Lan_GhiChu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ChuyenNoKhoDoi" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Quan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Phuong" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CoDH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaDMA" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TienDu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TienMat" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoHoaDonCu" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="ChanTienDu" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NgayChanTienDu" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="HIEULUC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NAMLD" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HIEUDH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="KhoaTienDu" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SoThanDHN" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DCHD" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Ngay_DCHD" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TongCongTruoc_DCHD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TienDuTruoc_DCHD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name_PC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IP_PC" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DangNgan_DienThoai" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.DIEUCHINH_HD" Member="DIEUCHINH_HDs">
    <Type Name="DIEUCHINH_HD">
      <Column Name="ID_DIEUCHINH_HD" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PHIEU_DC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGAY_VB" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FK_HOADON" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GIABAN_DC" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="THUE_DC" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="PHI_DC" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TONGCONG_DC" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="GB_DC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DM_DC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TILESH_DC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TILEHCSN_DC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TILESX_DC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TILEDV_DC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TIEUTHU_DC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGAY_DC" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GIABAN_BD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="THUE_BD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="PHI_BD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TONGCONG_BD" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TIEUTHU_BD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TXL" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="GiaBieu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DinhMuc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TangGiam" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoHoaDon" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="SoPhieu" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="GIABAN_END" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="THUE_END" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="PHI_END" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TONGCONG_END" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="ChuanThu1" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TT_QuetTam" Member="TT_QuetTams">
    <Type Name="TT_QuetTam">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaHD" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoHoaDon" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SoPhieu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TT_DichVuThu" Member="TT_DichVuThus">
    <Type Name="TT_DichVuThu">
      <Column Name="MaHD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoHoaDon" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DanhBo" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="Nam" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ky" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoTien" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Phi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TienDu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenDichVu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TenNganHang" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IDDichVu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDGiaoDich" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TT_DichVuThuTong" Member="TT_DichVuThuTongs">
    <Type Name="TT_DichVuThuTong">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DanhBo" Type="System.String" DbType="Char(11)" CanBeNull="true" />
      <Column Name="MaHDs" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SoHoaDons" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SoTien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PhiMoNuoc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TienDu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TongCong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenDichVu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IDGiaoDich" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TT_KiemTraHienTruong" Member="TT_KiemTraHienTruongs">
    <Type Name="TT_KiemTraHienTruong">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DanhBo" Type="System.String" DbType="Char(11)" CanBeNull="true" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="NoiDung" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TT_GuiThongBao" Member="TT_GuiThongBaos">
    <Type Name="TT_GuiThongBao">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DanhBo" Type="System.String" DbType="Char(11)" CanBeNull="true" />
      <Column Name="[In]" Member="In" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TT_DongNuoc" Member="TT_DongNuocs">
    <Type Name="TT_DongNuoc">
      <Column Name="MaDN" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DanhBo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MLT" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgayTBDN" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MaNV_DongNuoc" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayGiao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TroNgai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GhiChuTroNgai" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Huy" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreateBy_Old" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateDate_New" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TT_DongNuoc_TT_CTDongNuoc" Member="TT_CTDongNuocs" ThisKey="MaDN" OtherKey="MaDN" Type="TT_CTDongNuoc" />
      <Association Name="TT_DongNuoc_TT_KQDongNuoc" Member="TT_KQDongNuocs" ThisKey="MaDN" OtherKey="MaDN" Type="TT_KQDongNuoc" />
    </Type>
  </Table>
  <Table Name="dbo.TT_TongHopNo" Member="TT_TongHopNos">
    <Type Name="TT_TongHopNo">
      <Column Name="MaTHN" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DanhBo" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="KinhGui" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ChiSoCu" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ChiSoMoi" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TieuThu" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DinhMuc" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgayThanhToan" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TuNgay" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DenNgay" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NguoiKy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaTo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TT_TongHopNo_TT_CTTongHopNo" Member="TT_CTTongHopNos" ThisKey="MaTHN" OtherKey="MaTHN" Type="TT_CTTongHopNo" />
    </Type>
  </Table>
  <Function Name="dbo.TimKiem" Method="TimKiem" IsComposable="true">
    <Parameter Name="DanhBo" Parameter="danhBo" Type="System.String" DbType="VarChar(11)" />
    <Parameter Name="MLT" Parameter="mLT" Type="System.String" DbType="VarChar(11)" />
    <ElementType Name="TimKiemResult">
      <Column Name="MaHD" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DanhBo" Type="System.String" DbType="NVarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="MLT" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="HoTen" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(401)" CanBeNull="true" />
      <Column Name="GiaBieu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DinhMuc" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="SoHoaDon" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Ky" Type="System.String" DbType="VarChar(7)" CanBeNull="true" />
      <Column Name="TieuThu" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="GiaBan" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="ThueGTGT" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="PhiBVMT" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TongCong" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NgayGiaiTrach" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DangNgan" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="HanhThu" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="MaDN" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NgayDN" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayMN" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayDoc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CODE" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="ChiSo" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.TimKiemCu" Method="TimKiemCu" IsComposable="true">
    <Parameter Name="DanhBo" Parameter="danhBo" Type="System.String" DbType="VarChar(11)" />
    <Parameter Name="MLT" Parameter="mLT" Type="System.String" DbType="VarChar(11)" />
    <ElementType Name="TimKiemCuResult">
      <Column Name="MaHD" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DanhBo" Type="System.String" DbType="NVarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="MLT" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="HoTen" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(401)" CanBeNull="true" />
      <Column Name="GiaBieu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DinhMuc" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="SoHoaDon" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Ky" Type="System.String" DbType="VarChar(7)" CanBeNull="true" />
      <Column Name="TieuThu" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="GiaBan" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="ThueGTGT" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="PhiBVMT" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="TongCong" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NgayGiaiTrach" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DangNgan" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="HanhThu" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="MaDN" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NgayDN" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayMN" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayDoc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CODE" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="ChiSo" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>