select t1.LOTRINH,t2.MALOTRINH,SUBSTRING(LOTRINH,3,2) from
(select * from CAPNUOCTANHOA.dbo.TB_DULIEUKHACHHANG where SUBSTRING(LOTRINH,1,2)>=16)t1,
(select * from HOADON_TA.dbo.HOADON where MaNV_DangNgan is null)t2
where t1.DANHBO=t2.DANHBA and t1.LOTRINH!=t2.MALOTRINH

--update HOADON_TA.dbo.HOADON set dot=(select SUBSTRING(LOTRINH,1,2) from CAPNUOCTANHOA.dbo.TB_DULIEUKHACHHANG where CAPNUOCTANHOA.dbo.TB_DULIEUKHACHHANG.DANHBO=HOADON_TA.dbo.HOADON.DANHBA)
--,may=(select SUBSTRING(LOTRINH,3,2) from CAPNUOCTANHOA.dbo.TB_DULIEUKHACHHANG where CAPNUOCTANHOA.dbo.TB_DULIEUKHACHHANG.DANHBO=HOADON_TA.dbo.HOADON.DANHBA)
--,MALOTRINH=(select LOTRINH from CAPNUOCTANHOA.dbo.TB_DULIEUKHACHHANG where CAPNUOCTANHOA.dbo.TB_DULIEUKHACHHANG.DANHBO=HOADON_TA.dbo.HOADON.DANHBA)
--where ID_HOADON in (select t2.ID_HOADON from
--(select * from CAPNUOCTANHOA.dbo.TB_DULIEUKHACHHANG where SUBSTRING(LOTRINH,1,2)>=16)t1,
--(select * from HOADON_TA.dbo.HOADON where MaNV_DangNgan is null)t2
--where t1.DANHBO=t2.DANHBA and t1.LOTRINH!=t2.MALOTRINH)