<?xml version="1.0" encoding="utf-8"?><Database Name="KTCN_CongVan" Class="dbKTCN_CongVanDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=192.168.90.9;Initial Catalog=KTCN_CongVan;Persist Security Info=True;User ID=sa" SettingsObjectName="KTCN_CongVan.Properties.Settings" SettingsPropertyName="KTCN_CongVanConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CongVanDi" Member="CongVanDis">
    <Type Name="CongVanDi">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoCongVan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgayNhan" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CongVanCongTy" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NoiDung" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LoaiCongVan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BanChinh" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NoiNhan" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="HetHan" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NgayHetHan" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CongVanDen" Member="CongVanDens">
    <Type Name="CongVanDen">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SoCongVan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgayCongVan" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DonViPhatHanh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NgayNhan" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NoiDung" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LoaiCongVan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NoiNhan" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="HetHan" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NgayHetHan" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>