#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTKS_ChungCu.LinQ
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ChungCu")]
	public partial class DB_KTKS_DonKHDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DB_KTKS_DonKHDataContext() : 
				base(global::KTKS_ChungCu.Properties.Settings.Default.KTKS_DonKHConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DB_KTKS_DonKHDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_KTKS_DonKHDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_KTKS_DonKHDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_KTKS_DonKHDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ChungTu> ChungTus
		{
			get
			{
				return this.GetTable<ChungTu>();
			}
		}
		
		public System.Data.Linq.Table<TTKhachHang> TTKhachHangs
		{
			get
			{
				return this.GetTable<TTKhachHang>();
			}
		}
		
		public System.Data.Linq.Table<CTChungTu> CTChungTus
		{
			get
			{
				return this.GetTable<CTChungTu>();
			}
		}
		
		public System.Data.Linq.Table<LichSuChungTu> LichSuChungTus
		{
			get
			{
				return this.GetTable<LichSuChungTu>();
			}
		}
		
		public System.Data.Linq.Table<LoaiChungTu> LoaiChungTus
		{
			get
			{
				return this.GetTable<LoaiChungTu>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChungTu")]
	public partial class ChungTu
	{
		
		private string _MaCT;
		
		private string _HoTen;
		
		private string _DiaChi;
		
		private int _SoNKTong;
		
		private int _SoNKDaCap;
		
		private int _SoNKCat;
		
		private int _SoNKNhan;
		
		private int _SoNKConLai;
		
		private bool _YeuCauCat;
		
		private System.Nullable<decimal> _SoPhieu;
		
		private System.Nullable<int> _CatNK_MaCN;
		
		private string _CatNK_DanhBo;
		
		private string _CatNK_HoTen;
		
		private string _CatNK_DiaChi;
		
		private System.Nullable<int> _CatNK_SoNKCat;
		
		private System.Nullable<int> _MaLCT;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private System.Nullable<int> _CreateBy;
		
		private System.Nullable<System.DateTime> _ModifyDate;
		
		private System.Nullable<int> _ModifyBy;
		
		public ChungTu()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCT", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaCT
		{
			get
			{
				return this._MaCT;
			}
			set
			{
				if ((this._MaCT != value))
				{
					this._MaCT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(MAX)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this._HoTen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(MAX)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this._DiaChi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoNKTong", DbType="Int NOT NULL")]
		public int SoNKTong
		{
			get
			{
				return this._SoNKTong;
			}
			set
			{
				if ((this._SoNKTong != value))
				{
					this._SoNKTong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoNKDaCap", DbType="Int NOT NULL")]
		public int SoNKDaCap
		{
			get
			{
				return this._SoNKDaCap;
			}
			set
			{
				if ((this._SoNKDaCap != value))
				{
					this._SoNKDaCap = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoNKCat", DbType="Int NOT NULL")]
		public int SoNKCat
		{
			get
			{
				return this._SoNKCat;
			}
			set
			{
				if ((this._SoNKCat != value))
				{
					this._SoNKCat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoNKNhan", DbType="Int NOT NULL")]
		public int SoNKNhan
		{
			get
			{
				return this._SoNKNhan;
			}
			set
			{
				if ((this._SoNKNhan != value))
				{
					this._SoNKNhan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoNKConLai", DbType="Int NOT NULL")]
		public int SoNKConLai
		{
			get
			{
				return this._SoNKConLai;
			}
			set
			{
				if ((this._SoNKConLai != value))
				{
					this._SoNKConLai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YeuCauCat", DbType="Bit NOT NULL")]
		public bool YeuCauCat
		{
			get
			{
				return this._YeuCauCat;
			}
			set
			{
				if ((this._YeuCauCat != value))
				{
					this._YeuCauCat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoPhieu", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> SoPhieu
		{
			get
			{
				return this._SoPhieu;
			}
			set
			{
				if ((this._SoPhieu != value))
				{
					this._SoPhieu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatNK_MaCN", DbType="Int")]
		public System.Nullable<int> CatNK_MaCN
		{
			get
			{
				return this._CatNK_MaCN;
			}
			set
			{
				if ((this._CatNK_MaCN != value))
				{
					this._CatNK_MaCN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatNK_DanhBo", DbType="NVarChar(50)")]
		public string CatNK_DanhBo
		{
			get
			{
				return this._CatNK_DanhBo;
			}
			set
			{
				if ((this._CatNK_DanhBo != value))
				{
					this._CatNK_DanhBo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatNK_HoTen", DbType="NVarChar(MAX)")]
		public string CatNK_HoTen
		{
			get
			{
				return this._CatNK_HoTen;
			}
			set
			{
				if ((this._CatNK_HoTen != value))
				{
					this._CatNK_HoTen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatNK_DiaChi", DbType="NVarChar(MAX)")]
		public string CatNK_DiaChi
		{
			get
			{
				return this._CatNK_DiaChi;
			}
			set
			{
				if ((this._CatNK_DiaChi != value))
				{
					this._CatNK_DiaChi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatNK_SoNKCat", DbType="Int")]
		public System.Nullable<int> CatNK_SoNKCat
		{
			get
			{
				return this._CatNK_SoNKCat;
			}
			set
			{
				if ((this._CatNK_SoNKCat != value))
				{
					this._CatNK_SoNKCat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLCT", DbType="Int")]
		public System.Nullable<int> MaLCT
		{
			get
			{
				return this._MaLCT;
			}
			set
			{
				if ((this._MaLCT != value))
				{
					this._MaLCT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this._CreateDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateBy", DbType="Int")]
		public System.Nullable<int> CreateBy
		{
			get
			{
				return this._CreateBy;
			}
			set
			{
				if ((this._CreateBy != value))
				{
					this._CreateBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifyDate
		{
			get
			{
				return this._ModifyDate;
			}
			set
			{
				if ((this._ModifyDate != value))
				{
					this._ModifyDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyBy", DbType="Int")]
		public System.Nullable<int> ModifyBy
		{
			get
			{
				return this._ModifyBy;
			}
			set
			{
				if ((this._ModifyBy != value))
				{
					this._ModifyBy = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TTKhachHang")]
	public partial class TTKhachHang
	{
		
		private string _Khu;
		
		private string _Dot;
		
		private string _DanhBo;
		
		private string _CD;
		
		private string _CuLy;
		
		private string _MSTLK;
		
		private string _GiaoUoc;
		
		private string _HoTen;
		
		private string _DC1;
		
		private string _DC2;
		
		private string _MSKH;
		
		private string _MSCQ;
		
		private string _GB;
		
		private string _SH;
		
		private string _HCSN;
		
		private string _SX;
		
		private string _DV;
		
		private string _TGDM;
		
		private string _Ky;
		
		private string _Nam;
		
		private string _Code;
		
		private string _CodeFu;
		
		private string _CSCu;
		
		private string _CSMoi;
		
		private string _RT;
		
		private string _NgayDSKT;
		
		private string _NgayDSKN;
		
		private string _ChuKyDS;
		
		private string _LNCC;
		
		private string _LNCT;
		
		private string _LNBuToiThieu;
		
		private string _LNSH;
		
		private string _LNHCSN;
		
		private string _LNSX;
		
		private string _LNDV;
		
		private string _CuonGCS;
		
		private string _CuonSTT;
		
		private string _GiaBan;
		
		private string _ThueGTGT;
		
		private string _PhiBVMT;
		
		private string _TongCong;
		
		private string _GiaBanBuToiThieu;
		
		private string _ThueGTGTBuToiThieu;
		
		private string _PhiBVMTBuToiThieu;
		
		private string _TongCongBuToiThieu;
		
		private string _SoPhatHanh;
		
		private string _SoHoaDon;
		
		private string _NgayPhatHanh;
		
		private string _Quan;
		
		private string _Phuong;
		
		private string _SoDHN;
		
		private string _MSThue;
		
		private string _TileTieuThu;
		
		private string _NgayGanDHN;
		
		private string _SoHo;
		
		public TTKhachHang()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Khu", DbType="NVarChar(50)")]
		public string Khu
		{
			get
			{
				return this._Khu;
			}
			set
			{
				if ((this._Khu != value))
				{
					this._Khu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dot", DbType="NVarChar(50)")]
		public string Dot
		{
			get
			{
				return this._Dot;
			}
			set
			{
				if ((this._Dot != value))
				{
					this._Dot = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DanhBo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DanhBo
		{
			get
			{
				return this._DanhBo;
			}
			set
			{
				if ((this._DanhBo != value))
				{
					this._DanhBo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CD", DbType="NVarChar(50)")]
		public string CD
		{
			get
			{
				return this._CD;
			}
			set
			{
				if ((this._CD != value))
				{
					this._CD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CuLy", DbType="NVarChar(50)")]
		public string CuLy
		{
			get
			{
				return this._CuLy;
			}
			set
			{
				if ((this._CuLy != value))
				{
					this._CuLy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSTLK", DbType="NVarChar(50)")]
		public string MSTLK
		{
			get
			{
				return this._MSTLK;
			}
			set
			{
				if ((this._MSTLK != value))
				{
					this._MSTLK = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaoUoc", DbType="NVarChar(50)")]
		public string GiaoUoc
		{
			get
			{
				return this._GiaoUoc;
			}
			set
			{
				if ((this._GiaoUoc != value))
				{
					this._GiaoUoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(MAX)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this._HoTen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DC1", DbType="NVarChar(50)")]
		public string DC1
		{
			get
			{
				return this._DC1;
			}
			set
			{
				if ((this._DC1 != value))
				{
					this._DC1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DC2", DbType="NVarChar(100)")]
		public string DC2
		{
			get
			{
				return this._DC2;
			}
			set
			{
				if ((this._DC2 != value))
				{
					this._DC2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSKH", DbType="NVarChar(50)")]
		public string MSKH
		{
			get
			{
				return this._MSKH;
			}
			set
			{
				if ((this._MSKH != value))
				{
					this._MSKH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSCQ", DbType="NVarChar(50)")]
		public string MSCQ
		{
			get
			{
				return this._MSCQ;
			}
			set
			{
				if ((this._MSCQ != value))
				{
					this._MSCQ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GB", DbType="NVarChar(50)")]
		public string GB
		{
			get
			{
				return this._GB;
			}
			set
			{
				if ((this._GB != value))
				{
					this._GB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SH", DbType="NVarChar(50)")]
		public string SH
		{
			get
			{
				return this._SH;
			}
			set
			{
				if ((this._SH != value))
				{
					this._SH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HCSN", DbType="NVarChar(50)")]
		public string HCSN
		{
			get
			{
				return this._HCSN;
			}
			set
			{
				if ((this._HCSN != value))
				{
					this._HCSN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SX", DbType="NVarChar(50)")]
		public string SX
		{
			get
			{
				return this._SX;
			}
			set
			{
				if ((this._SX != value))
				{
					this._SX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DV", DbType="NVarChar(50)")]
		public string DV
		{
			get
			{
				return this._DV;
			}
			set
			{
				if ((this._DV != value))
				{
					this._DV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TGDM", DbType="NVarChar(50)")]
		public string TGDM
		{
			get
			{
				return this._TGDM;
			}
			set
			{
				if ((this._TGDM != value))
				{
					this._TGDM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ky", DbType="NVarChar(50)")]
		public string Ky
		{
			get
			{
				return this._Ky;
			}
			set
			{
				if ((this._Ky != value))
				{
					this._Ky = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nam", DbType="NVarChar(50)")]
		public string Nam
		{
			get
			{
				return this._Nam;
			}
			set
			{
				if ((this._Nam != value))
				{
					this._Nam = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NVarChar(50)")]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this._Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CodeFu", DbType="NVarChar(50)")]
		public string CodeFu
		{
			get
			{
				return this._CodeFu;
			}
			set
			{
				if ((this._CodeFu != value))
				{
					this._CodeFu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CSCu", DbType="NVarChar(50)")]
		public string CSCu
		{
			get
			{
				return this._CSCu;
			}
			set
			{
				if ((this._CSCu != value))
				{
					this._CSCu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CSMoi", DbType="NVarChar(50)")]
		public string CSMoi
		{
			get
			{
				return this._CSMoi;
			}
			set
			{
				if ((this._CSMoi != value))
				{
					this._CSMoi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RT", DbType="NVarChar(50)")]
		public string RT
		{
			get
			{
				return this._RT;
			}
			set
			{
				if ((this._RT != value))
				{
					this._RT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDSKT", DbType="NVarChar(50)")]
		public string NgayDSKT
		{
			get
			{
				return this._NgayDSKT;
			}
			set
			{
				if ((this._NgayDSKT != value))
				{
					this._NgayDSKT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDSKN", DbType="NVarChar(50)")]
		public string NgayDSKN
		{
			get
			{
				return this._NgayDSKN;
			}
			set
			{
				if ((this._NgayDSKN != value))
				{
					this._NgayDSKN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChuKyDS", DbType="NVarChar(50)")]
		public string ChuKyDS
		{
			get
			{
				return this._ChuKyDS;
			}
			set
			{
				if ((this._ChuKyDS != value))
				{
					this._ChuKyDS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LNCC", DbType="NVarChar(50)")]
		public string LNCC
		{
			get
			{
				return this._LNCC;
			}
			set
			{
				if ((this._LNCC != value))
				{
					this._LNCC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LNCT", DbType="NVarChar(50)")]
		public string LNCT
		{
			get
			{
				return this._LNCT;
			}
			set
			{
				if ((this._LNCT != value))
				{
					this._LNCT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LNBuToiThieu", DbType="NVarChar(50)")]
		public string LNBuToiThieu
		{
			get
			{
				return this._LNBuToiThieu;
			}
			set
			{
				if ((this._LNBuToiThieu != value))
				{
					this._LNBuToiThieu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LNSH", DbType="NVarChar(50)")]
		public string LNSH
		{
			get
			{
				return this._LNSH;
			}
			set
			{
				if ((this._LNSH != value))
				{
					this._LNSH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LNHCSN", DbType="NVarChar(50)")]
		public string LNHCSN
		{
			get
			{
				return this._LNHCSN;
			}
			set
			{
				if ((this._LNHCSN != value))
				{
					this._LNHCSN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LNSX", DbType="NVarChar(50)")]
		public string LNSX
		{
			get
			{
				return this._LNSX;
			}
			set
			{
				if ((this._LNSX != value))
				{
					this._LNSX = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LNDV", DbType="NVarChar(50)")]
		public string LNDV
		{
			get
			{
				return this._LNDV;
			}
			set
			{
				if ((this._LNDV != value))
				{
					this._LNDV = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CuonGCS", DbType="NVarChar(50)")]
		public string CuonGCS
		{
			get
			{
				return this._CuonGCS;
			}
			set
			{
				if ((this._CuonGCS != value))
				{
					this._CuonGCS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CuonSTT", DbType="NVarChar(50)")]
		public string CuonSTT
		{
			get
			{
				return this._CuonSTT;
			}
			set
			{
				if ((this._CuonSTT != value))
				{
					this._CuonSTT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaBan", DbType="NVarChar(50)")]
		public string GiaBan
		{
			get
			{
				return this._GiaBan;
			}
			set
			{
				if ((this._GiaBan != value))
				{
					this._GiaBan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThueGTGT", DbType="NVarChar(50)")]
		public string ThueGTGT
		{
			get
			{
				return this._ThueGTGT;
			}
			set
			{
				if ((this._ThueGTGT != value))
				{
					this._ThueGTGT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhiBVMT", DbType="NVarChar(50)")]
		public string PhiBVMT
		{
			get
			{
				return this._PhiBVMT;
			}
			set
			{
				if ((this._PhiBVMT != value))
				{
					this._PhiBVMT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongCong", DbType="NVarChar(50)")]
		public string TongCong
		{
			get
			{
				return this._TongCong;
			}
			set
			{
				if ((this._TongCong != value))
				{
					this._TongCong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaBanBuToiThieu", DbType="NVarChar(50)")]
		public string GiaBanBuToiThieu
		{
			get
			{
				return this._GiaBanBuToiThieu;
			}
			set
			{
				if ((this._GiaBanBuToiThieu != value))
				{
					this._GiaBanBuToiThieu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThueGTGTBuToiThieu", DbType="NVarChar(50)")]
		public string ThueGTGTBuToiThieu
		{
			get
			{
				return this._ThueGTGTBuToiThieu;
			}
			set
			{
				if ((this._ThueGTGTBuToiThieu != value))
				{
					this._ThueGTGTBuToiThieu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhiBVMTBuToiThieu", DbType="NVarChar(50)")]
		public string PhiBVMTBuToiThieu
		{
			get
			{
				return this._PhiBVMTBuToiThieu;
			}
			set
			{
				if ((this._PhiBVMTBuToiThieu != value))
				{
					this._PhiBVMTBuToiThieu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongCongBuToiThieu", DbType="NVarChar(50)")]
		public string TongCongBuToiThieu
		{
			get
			{
				return this._TongCongBuToiThieu;
			}
			set
			{
				if ((this._TongCongBuToiThieu != value))
				{
					this._TongCongBuToiThieu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoPhatHanh", DbType="NVarChar(50)")]
		public string SoPhatHanh
		{
			get
			{
				return this._SoPhatHanh;
			}
			set
			{
				if ((this._SoPhatHanh != value))
				{
					this._SoPhatHanh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoHoaDon", DbType="NVarChar(50)")]
		public string SoHoaDon
		{
			get
			{
				return this._SoHoaDon;
			}
			set
			{
				if ((this._SoHoaDon != value))
				{
					this._SoHoaDon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayPhatHanh", DbType="NVarChar(50)")]
		public string NgayPhatHanh
		{
			get
			{
				return this._NgayPhatHanh;
			}
			set
			{
				if ((this._NgayPhatHanh != value))
				{
					this._NgayPhatHanh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quan", DbType="NVarChar(50)")]
		public string Quan
		{
			get
			{
				return this._Quan;
			}
			set
			{
				if ((this._Quan != value))
				{
					this._Quan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phuong", DbType="NVarChar(50)")]
		public string Phuong
		{
			get
			{
				return this._Phuong;
			}
			set
			{
				if ((this._Phuong != value))
				{
					this._Phuong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDHN", DbType="NVarChar(50)")]
		public string SoDHN
		{
			get
			{
				return this._SoDHN;
			}
			set
			{
				if ((this._SoDHN != value))
				{
					this._SoDHN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MSThue", DbType="NVarChar(50)")]
		public string MSThue
		{
			get
			{
				return this._MSThue;
			}
			set
			{
				if ((this._MSThue != value))
				{
					this._MSThue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TileTieuThu", DbType="NVarChar(50)")]
		public string TileTieuThu
		{
			get
			{
				return this._TileTieuThu;
			}
			set
			{
				if ((this._TileTieuThu != value))
				{
					this._TileTieuThu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayGanDHN", DbType="NVarChar(50)")]
		public string NgayGanDHN
		{
			get
			{
				return this._NgayGanDHN;
			}
			set
			{
				if ((this._NgayGanDHN != value))
				{
					this._NgayGanDHN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoHo", DbType="NVarChar(50)")]
		public string SoHo
		{
			get
			{
				return this._SoHo;
			}
			set
			{
				if ((this._SoHo != value))
				{
					this._SoHo = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CTChungTu")]
	public partial class CTChungTu
	{
		
		private string _DanhBo;
		
		private string _MaCT;
		
		private string _DienThoai;
		
		private bool _SoChinh;
		
		private int _SoNKDangKy;
		
		private System.Nullable<int> _ThoiHan;
		
		private System.Nullable<System.DateTime> _NgayHetHan;
		
		private string _GhiChu;
		
		private string _Lo;
		
		private string _Phong;
		
		private bool _Cat;
		
		private System.Nullable<int> _SoLuongDC_YCC;
		
		private bool _YeuCauCat;
		
		private System.Nullable<decimal> _SoPhieu;
		
		private System.Nullable<int> _CatNK_MaCN;
		
		private string _CatNK_DanhBo;
		
		private string _CatNK_HoTen;
		
		private string _CatNK_DiaChi;
		
		private System.Nullable<int> _CatNK_SoNKCat;
		
		private bool _YeuCauCat2;
		
		private System.Nullable<decimal> _SoPhieu2;
		
		private System.Nullable<int> _CatNK_MaCN2;
		
		private string _CatNK_DanhBo2;
		
		private string _CatNK_HoTen2;
		
		private string _CatNK_DiaChi2;
		
		private System.Nullable<int> _CatNK_SoNKCat2;
		
		private bool _YeuCauCat3;
		
		private System.Nullable<decimal> _SoPhieu3;
		
		private System.Nullable<int> _CatNK_MaCN3;
		
		private string _CatNK_DanhBo3;
		
		private string _CatNK_HoTen3;
		
		private string _CatNK_DiaChi3;
		
		private System.Nullable<int> _CatNK_SoNKCat3;
		
		private bool _YeuCauCat4;
		
		private System.Nullable<decimal> _SoPhieu4;
		
		private System.Nullable<int> _CatNK_MaCN4;
		
		private string _CatNK_DanhBo4;
		
		private string _CatNK_HoTen4;
		
		private string _CatNK_DiaChi4;
		
		private System.Nullable<int> _CatNK_SoNKCat4;
		
		private bool _YeuCauCat5;
		
		private System.Nullable<decimal> _SoPhieu5;
		
		private System.Nullable<int> _CatNK_MaCN5;
		
		private string _CatNK_DanhBo5;
		
		private string _CatNK_HoTen5;
		
		private string _CatNK_DiaChi5;
		
		private System.Nullable<int> _CatNK_SoNKCat5;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private System.Nullable<int> _CreateBy;
		
		private System.Nullable<System.DateTime> _ModifyDate;
		
		private System.Nullable<int> _ModifyBy;
		
		public CTChungTu()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DanhBo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DanhBo
		{
			get
			{
				return this._DanhBo;
			}
			set
			{
				if ((this._DanhBo != value))
				{
					this._DanhBo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCT", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaCT
		{
			get
			{
				return this._MaCT;
			}
			set
			{
				if ((this._MaCT != value))
				{
					this._MaCT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienThoai", DbType="NVarChar(50)")]
		public string DienThoai
		{
			get
			{
				return this._DienThoai;
			}
			set
			{
				if ((this._DienThoai != value))
				{
					this._DienThoai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoChinh", DbType="Bit NOT NULL")]
		public bool SoChinh
		{
			get
			{
				return this._SoChinh;
			}
			set
			{
				if ((this._SoChinh != value))
				{
					this._SoChinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoNKDangKy", DbType="Int NOT NULL")]
		public int SoNKDangKy
		{
			get
			{
				return this._SoNKDangKy;
			}
			set
			{
				if ((this._SoNKDangKy != value))
				{
					this._SoNKDangKy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiHan", DbType="Int")]
		public System.Nullable<int> ThoiHan
		{
			get
			{
				return this._ThoiHan;
			}
			set
			{
				if ((this._ThoiHan != value))
				{
					this._ThoiHan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayHetHan", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayHetHan
		{
			get
			{
				return this._NgayHetHan;
			}
			set
			{
				if ((this._NgayHetHan != value))
				{
					this._NgayHetHan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(MAX)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this._GhiChu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lo", DbType="NVarChar(50)")]
		public string Lo
		{
			get
			{
				return this._Lo;
			}
			set
			{
				if ((this._Lo != value))
				{
					this._Lo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phong", DbType="NVarChar(50)")]
		public string Phong
		{
			get
			{
				return this._Phong;
			}
			set
			{
				if ((this._Phong != value))
				{
					this._Phong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cat", DbType="Bit NOT NULL")]
		public bool Cat
		{
			get
			{
				return this._Cat;
			}
			set
			{
				if ((this._Cat != value))
				{
					this._Cat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongDC_YCC", DbType="Int")]
		public System.Nullable<int> SoLuongDC_YCC
		{
			get
			{
				return this._SoLuongDC_YCC;
			}
			set
			{
				if ((this._SoLuongDC_YCC != value))
				{
					this._SoLuongDC_YCC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YeuCauCat", DbType="Bit NOT NULL")]
		public bool YeuCauCat
		{
			get
			{
				return this._YeuCauCat;
			}
			set
			{
				if ((this._YeuCauCat != value))
				{
					this._YeuCauCat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoPhieu", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> SoPhieu
		{
			get
			{
				return this._SoPhieu;
			}
			set
			{
				if ((this._SoPhieu != value))
				{
					this._SoPhieu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatNK_MaCN", DbType="Int")]
		public System.Nullable<int> CatNK_MaCN
		{
			get
			{
				return this._CatNK_MaCN;
			}
			set
			{
				if ((this._CatNK_MaCN != value))
				{
					this._CatNK_MaCN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatNK_DanhBo", DbType="NVarChar(50)")]
		public string CatNK_DanhBo
		{
			get
			{
				return this._CatNK_DanhBo;
			}
			set
			{
				if ((this._CatNK_DanhBo != value))
				{
					this._CatNK_DanhBo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatNK_HoTen", DbType="NVarChar(200)")]
		public string CatNK_HoTen
		{
			get
			{
				return this._CatNK_HoTen;
			}
			set
			{
				if ((this._CatNK_HoTen != value))
				{
					this._CatNK_HoTen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatNK_DiaChi", DbType="NVarChar(MAX)")]
		public string CatNK_DiaChi
		{
			get
			{
				return this._CatNK_DiaChi;
			}
			set
			{
				if ((this._CatNK_DiaChi != value))
				{
					this._CatNK_DiaChi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatNK_SoNKCat", DbType="Int")]
		public System.Nullable<int> CatNK_SoNKCat
		{
			get
			{
				return this._CatNK_SoNKCat;
			}
			set
			{
				if ((this._CatNK_SoNKCat != value))
				{
					this._CatNK_SoNKCat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YeuCauCat2", DbType="Bit NOT NULL")]
		public bool YeuCauCat2
		{
			get
			{
				return this._YeuCauCat2;
			}
			set
			{
				if ((this._YeuCauCat2 != value))
				{
					this._YeuCauCat2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoPhieu2", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> SoPhieu2
		{
			get
			{
				return this._SoPhieu2;
			}
			set
			{
				if ((this._SoPhieu2 != value))
				{
					this._SoPhieu2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatNK_MaCN2", DbType="Int")]
		public System.Nullable<int> CatNK_MaCN2
		{
			get
			{
				return this._CatNK_MaCN2;
			}
			set
			{
				if ((this._CatNK_MaCN2 != value))
				{
					this._CatNK_MaCN2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatNK_DanhBo2", DbType="NVarChar(50)")]
		public string CatNK_DanhBo2
		{
			get
			{
				return this._CatNK_DanhBo2;
			}
			set
			{
				if ((this._CatNK_DanhBo2 != value))
				{
					this._CatNK_DanhBo2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatNK_HoTen2", DbType="NVarChar(MAX)")]
		public string CatNK_HoTen2
		{
			get
			{
				return this._CatNK_HoTen2;
			}
			set
			{
				if ((this._CatNK_HoTen2 != value))
				{
					this._CatNK_HoTen2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatNK_DiaChi2", DbType="NVarChar(MAX)")]
		public string CatNK_DiaChi2
		{
			get
			{
				return this._CatNK_DiaChi2;
			}
			set
			{
				if ((this._CatNK_DiaChi2 != value))
				{
					this._CatNK_DiaChi2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatNK_SoNKCat2", DbType="Int")]
		public System.Nullable<int> CatNK_SoNKCat2
		{
			get
			{
				return this._CatNK_SoNKCat2;
			}
			set
			{
				if ((this._CatNK_SoNKCat2 != value))
				{
					this._CatNK_SoNKCat2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YeuCauCat3", DbType="Bit NOT NULL")]
		public bool YeuCauCat3
		{
			get
			{
				return this._YeuCauCat3;
			}
			set
			{
				if ((this._YeuCauCat3 != value))
				{
					this._YeuCauCat3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoPhieu3", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> SoPhieu3
		{
			get
			{
				return this._SoPhieu3;
			}
			set
			{
				if ((this._SoPhieu3 != value))
				{
					this._SoPhieu3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatNK_MaCN3", DbType="Int")]
		public System.Nullable<int> CatNK_MaCN3
		{
			get
			{
				return this._CatNK_MaCN3;
			}
			set
			{
				if ((this._CatNK_MaCN3 != value))
				{
					this._CatNK_MaCN3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatNK_DanhBo3", DbType="NVarChar(50)")]
		public string CatNK_DanhBo3
		{
			get
			{
				return this._CatNK_DanhBo3;
			}
			set
			{
				if ((this._CatNK_DanhBo3 != value))
				{
					this._CatNK_DanhBo3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatNK_HoTen3", DbType="NVarChar(200)")]
		public string CatNK_HoTen3
		{
			get
			{
				return this._CatNK_HoTen3;
			}
			set
			{
				if ((this._CatNK_HoTen3 != value))
				{
					this._CatNK_HoTen3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatNK_DiaChi3", DbType="NVarChar(MAX)")]
		public string CatNK_DiaChi3
		{
			get
			{
				return this._CatNK_DiaChi3;
			}
			set
			{
				if ((this._CatNK_DiaChi3 != value))
				{
					this._CatNK_DiaChi3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatNK_SoNKCat3", DbType="Int")]
		public System.Nullable<int> CatNK_SoNKCat3
		{
			get
			{
				return this._CatNK_SoNKCat3;
			}
			set
			{
				if ((this._CatNK_SoNKCat3 != value))
				{
					this._CatNK_SoNKCat3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YeuCauCat4", DbType="Bit NOT NULL")]
		public bool YeuCauCat4
		{
			get
			{
				return this._YeuCauCat4;
			}
			set
			{
				if ((this._YeuCauCat4 != value))
				{
					this._YeuCauCat4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoPhieu4", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> SoPhieu4
		{
			get
			{
				return this._SoPhieu4;
			}
			set
			{
				if ((this._SoPhieu4 != value))
				{
					this._SoPhieu4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatNK_MaCN4", DbType="Int")]
		public System.Nullable<int> CatNK_MaCN4
		{
			get
			{
				return this._CatNK_MaCN4;
			}
			set
			{
				if ((this._CatNK_MaCN4 != value))
				{
					this._CatNK_MaCN4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatNK_DanhBo4", DbType="NVarChar(50)")]
		public string CatNK_DanhBo4
		{
			get
			{
				return this._CatNK_DanhBo4;
			}
			set
			{
				if ((this._CatNK_DanhBo4 != value))
				{
					this._CatNK_DanhBo4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatNK_HoTen4", DbType="NVarChar(200)")]
		public string CatNK_HoTen4
		{
			get
			{
				return this._CatNK_HoTen4;
			}
			set
			{
				if ((this._CatNK_HoTen4 != value))
				{
					this._CatNK_HoTen4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatNK_DiaChi4", DbType="NVarChar(MAX)")]
		public string CatNK_DiaChi4
		{
			get
			{
				return this._CatNK_DiaChi4;
			}
			set
			{
				if ((this._CatNK_DiaChi4 != value))
				{
					this._CatNK_DiaChi4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatNK_SoNKCat4", DbType="Int")]
		public System.Nullable<int> CatNK_SoNKCat4
		{
			get
			{
				return this._CatNK_SoNKCat4;
			}
			set
			{
				if ((this._CatNK_SoNKCat4 != value))
				{
					this._CatNK_SoNKCat4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YeuCauCat5", DbType="Bit NOT NULL")]
		public bool YeuCauCat5
		{
			get
			{
				return this._YeuCauCat5;
			}
			set
			{
				if ((this._YeuCauCat5 != value))
				{
					this._YeuCauCat5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoPhieu5", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> SoPhieu5
		{
			get
			{
				return this._SoPhieu5;
			}
			set
			{
				if ((this._SoPhieu5 != value))
				{
					this._SoPhieu5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatNK_MaCN5", DbType="Int")]
		public System.Nullable<int> CatNK_MaCN5
		{
			get
			{
				return this._CatNK_MaCN5;
			}
			set
			{
				if ((this._CatNK_MaCN5 != value))
				{
					this._CatNK_MaCN5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatNK_DanhBo5", DbType="NVarChar(50)")]
		public string CatNK_DanhBo5
		{
			get
			{
				return this._CatNK_DanhBo5;
			}
			set
			{
				if ((this._CatNK_DanhBo5 != value))
				{
					this._CatNK_DanhBo5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatNK_HoTen5", DbType="NVarChar(200)")]
		public string CatNK_HoTen5
		{
			get
			{
				return this._CatNK_HoTen5;
			}
			set
			{
				if ((this._CatNK_HoTen5 != value))
				{
					this._CatNK_HoTen5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatNK_DiaChi5", DbType="NVarChar(MAX)")]
		public string CatNK_DiaChi5
		{
			get
			{
				return this._CatNK_DiaChi5;
			}
			set
			{
				if ((this._CatNK_DiaChi5 != value))
				{
					this._CatNK_DiaChi5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatNK_SoNKCat5", DbType="Int")]
		public System.Nullable<int> CatNK_SoNKCat5
		{
			get
			{
				return this._CatNK_SoNKCat5;
			}
			set
			{
				if ((this._CatNK_SoNKCat5 != value))
				{
					this._CatNK_SoNKCat5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this._CreateDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateBy", DbType="Int")]
		public System.Nullable<int> CreateBy
		{
			get
			{
				return this._CreateBy;
			}
			set
			{
				if ((this._CreateBy != value))
				{
					this._CreateBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifyDate
		{
			get
			{
				return this._ModifyDate;
			}
			set
			{
				if ((this._ModifyDate != value))
				{
					this._ModifyDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyBy", DbType="Int")]
		public System.Nullable<int> ModifyBy
		{
			get
			{
				return this._ModifyBy;
			}
			set
			{
				if ((this._ModifyBy != value))
				{
					this._ModifyBy = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LichSuChungTu")]
	public partial class LichSuChungTu
	{
		
		private decimal _MaLSCT;
		
		private string _DanhBo;
		
		private string _MaCT;
		
		private string _Lo;
		
		private string _Phong;
		
		private System.Nullable<int> _SoNKTong;
		
		private System.Nullable<int> _SoNKDangKy;
		
		private System.Nullable<int> _SoNKConLai;
		
		private System.Nullable<int> _ThoiHan;
		
		private System.Nullable<System.DateTime> _NgayHetHan;
		
		private System.Nullable<decimal> _SoPhieu;
		
		private System.Nullable<bool> _CatDM;
		
		private System.Nullable<int> _SoNKCat;
		
		private System.Nullable<int> _NhanNK_MaCN;
		
		private string _NhanNK_DanhBo;
		
		private string _NhanNK_HoTen;
		
		private string _NhanNK_DiaChi;
		
		private System.Nullable<bool> _NhanDM;
		
		private System.Nullable<bool> _YeuCauCat;
		
		private System.Nullable<int> _SoNKNhan;
		
		private System.Nullable<int> _CatNK_MaCN;
		
		private string _CatNK_DanhBo;
		
		private string _CatNK_HoTen;
		
		private string _CatNK_DiaChi;
		
		private string _GhiChu;
		
		private System.Nullable<decimal> _MaDon;
		
		private bool _ToXuLy;
		
		private System.Nullable<decimal> _MaDonTXL;
		
		private string _NguoiKy;
		
		private string _ChucVu;
		
		private bool _PhieuDuocKy;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private System.Nullable<int> _CreateBy;
		
		private System.Nullable<System.DateTime> _ModifyDate;
		
		private System.Nullable<int> _ModifyBy;
		
		public LichSuChungTu()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLSCT", DbType="Decimal(18,0) NOT NULL")]
		public decimal MaLSCT
		{
			get
			{
				return this._MaLSCT;
			}
			set
			{
				if ((this._MaLSCT != value))
				{
					this._MaLSCT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DanhBo", DbType="NVarChar(50)")]
		public string DanhBo
		{
			get
			{
				return this._DanhBo;
			}
			set
			{
				if ((this._DanhBo != value))
				{
					this._DanhBo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCT", DbType="NVarChar(50)")]
		public string MaCT
		{
			get
			{
				return this._MaCT;
			}
			set
			{
				if ((this._MaCT != value))
				{
					this._MaCT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Lo", DbType="NVarChar(50)")]
		public string Lo
		{
			get
			{
				return this._Lo;
			}
			set
			{
				if ((this._Lo != value))
				{
					this._Lo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phong", DbType="NVarChar(50)")]
		public string Phong
		{
			get
			{
				return this._Phong;
			}
			set
			{
				if ((this._Phong != value))
				{
					this._Phong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoNKTong", DbType="Int")]
		public System.Nullable<int> SoNKTong
		{
			get
			{
				return this._SoNKTong;
			}
			set
			{
				if ((this._SoNKTong != value))
				{
					this._SoNKTong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoNKDangKy", DbType="Int")]
		public System.Nullable<int> SoNKDangKy
		{
			get
			{
				return this._SoNKDangKy;
			}
			set
			{
				if ((this._SoNKDangKy != value))
				{
					this._SoNKDangKy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoNKConLai", DbType="Int")]
		public System.Nullable<int> SoNKConLai
		{
			get
			{
				return this._SoNKConLai;
			}
			set
			{
				if ((this._SoNKConLai != value))
				{
					this._SoNKConLai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiHan", DbType="Int")]
		public System.Nullable<int> ThoiHan
		{
			get
			{
				return this._ThoiHan;
			}
			set
			{
				if ((this._ThoiHan != value))
				{
					this._ThoiHan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayHetHan", DbType="Date")]
		public System.Nullable<System.DateTime> NgayHetHan
		{
			get
			{
				return this._NgayHetHan;
			}
			set
			{
				if ((this._NgayHetHan != value))
				{
					this._NgayHetHan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoPhieu", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> SoPhieu
		{
			get
			{
				return this._SoPhieu;
			}
			set
			{
				if ((this._SoPhieu != value))
				{
					this._SoPhieu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatDM", DbType="Bit")]
		public System.Nullable<bool> CatDM
		{
			get
			{
				return this._CatDM;
			}
			set
			{
				if ((this._CatDM != value))
				{
					this._CatDM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoNKCat", DbType="Int")]
		public System.Nullable<int> SoNKCat
		{
			get
			{
				return this._SoNKCat;
			}
			set
			{
				if ((this._SoNKCat != value))
				{
					this._SoNKCat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhanNK_MaCN", DbType="Int")]
		public System.Nullable<int> NhanNK_MaCN
		{
			get
			{
				return this._NhanNK_MaCN;
			}
			set
			{
				if ((this._NhanNK_MaCN != value))
				{
					this._NhanNK_MaCN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhanNK_DanhBo", DbType="NVarChar(50)")]
		public string NhanNK_DanhBo
		{
			get
			{
				return this._NhanNK_DanhBo;
			}
			set
			{
				if ((this._NhanNK_DanhBo != value))
				{
					this._NhanNK_DanhBo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhanNK_HoTen", DbType="NVarChar(MAX)")]
		public string NhanNK_HoTen
		{
			get
			{
				return this._NhanNK_HoTen;
			}
			set
			{
				if ((this._NhanNK_HoTen != value))
				{
					this._NhanNK_HoTen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhanNK_DiaChi", DbType="NVarChar(MAX)")]
		public string NhanNK_DiaChi
		{
			get
			{
				return this._NhanNK_DiaChi;
			}
			set
			{
				if ((this._NhanNK_DiaChi != value))
				{
					this._NhanNK_DiaChi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NhanDM", DbType="Bit")]
		public System.Nullable<bool> NhanDM
		{
			get
			{
				return this._NhanDM;
			}
			set
			{
				if ((this._NhanDM != value))
				{
					this._NhanDM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YeuCauCat", DbType="Bit")]
		public System.Nullable<bool> YeuCauCat
		{
			get
			{
				return this._YeuCauCat;
			}
			set
			{
				if ((this._YeuCauCat != value))
				{
					this._YeuCauCat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoNKNhan", DbType="Int")]
		public System.Nullable<int> SoNKNhan
		{
			get
			{
				return this._SoNKNhan;
			}
			set
			{
				if ((this._SoNKNhan != value))
				{
					this._SoNKNhan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatNK_MaCN", DbType="Int")]
		public System.Nullable<int> CatNK_MaCN
		{
			get
			{
				return this._CatNK_MaCN;
			}
			set
			{
				if ((this._CatNK_MaCN != value))
				{
					this._CatNK_MaCN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatNK_DanhBo", DbType="NVarChar(50)")]
		public string CatNK_DanhBo
		{
			get
			{
				return this._CatNK_DanhBo;
			}
			set
			{
				if ((this._CatNK_DanhBo != value))
				{
					this._CatNK_DanhBo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatNK_HoTen", DbType="NVarChar(200)")]
		public string CatNK_HoTen
		{
			get
			{
				return this._CatNK_HoTen;
			}
			set
			{
				if ((this._CatNK_HoTen != value))
				{
					this._CatNK_HoTen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatNK_DiaChi", DbType="NVarChar(MAX)")]
		public string CatNK_DiaChi
		{
			get
			{
				return this._CatNK_DiaChi;
			}
			set
			{
				if ((this._CatNK_DiaChi != value))
				{
					this._CatNK_DiaChi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(MAX)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this._GhiChu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDon", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MaDon
		{
			get
			{
				return this._MaDon;
			}
			set
			{
				if ((this._MaDon != value))
				{
					this._MaDon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ToXuLy", DbType="Bit NOT NULL")]
		public bool ToXuLy
		{
			get
			{
				return this._ToXuLy;
			}
			set
			{
				if ((this._ToXuLy != value))
				{
					this._ToXuLy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDonTXL", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> MaDonTXL
		{
			get
			{
				return this._MaDonTXL;
			}
			set
			{
				if ((this._MaDonTXL != value))
				{
					this._MaDonTXL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiKy", DbType="NVarChar(100)")]
		public string NguoiKy
		{
			get
			{
				return this._NguoiKy;
			}
			set
			{
				if ((this._NguoiKy != value))
				{
					this._NguoiKy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChucVu", DbType="NVarChar(100)")]
		public string ChucVu
		{
			get
			{
				return this._ChucVu;
			}
			set
			{
				if ((this._ChucVu != value))
				{
					this._ChucVu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhieuDuocKy", DbType="Bit NOT NULL")]
		public bool PhieuDuocKy
		{
			get
			{
				return this._PhieuDuocKy;
			}
			set
			{
				if ((this._PhieuDuocKy != value))
				{
					this._PhieuDuocKy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this._CreateDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateBy", DbType="Int")]
		public System.Nullable<int> CreateBy
		{
			get
			{
				return this._CreateBy;
			}
			set
			{
				if ((this._CreateBy != value))
				{
					this._CreateBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifyDate
		{
			get
			{
				return this._ModifyDate;
			}
			set
			{
				if ((this._ModifyDate != value))
				{
					this._ModifyDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyBy", DbType="Int")]
		public System.Nullable<int> ModifyBy
		{
			get
			{
				return this._ModifyBy;
			}
			set
			{
				if ((this._ModifyBy != value))
				{
					this._ModifyBy = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiChungTu")]
	public partial class LoaiChungTu
	{
		
		private int _MaLCT;
		
		private string _KyHieuLCT;
		
		private string _TenLCT;
		
		private System.Nullable<int> _ThoiHan;
		
		private System.Nullable<System.DateTime> _CreateDate;
		
		private System.Nullable<int> _CreateBy;
		
		private System.Nullable<System.DateTime> _ModifyDate;
		
		private System.Nullable<int> _ModifyBy;
		
		public LoaiChungTu()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLCT", DbType="Int NOT NULL")]
		public int MaLCT
		{
			get
			{
				return this._MaLCT;
			}
			set
			{
				if ((this._MaLCT != value))
				{
					this._MaLCT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KyHieuLCT", DbType="NVarChar(50)")]
		public string KyHieuLCT
		{
			get
			{
				return this._KyHieuLCT;
			}
			set
			{
				if ((this._KyHieuLCT != value))
				{
					this._KyHieuLCT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLCT", DbType="NVarChar(MAX)")]
		public string TenLCT
		{
			get
			{
				return this._TenLCT;
			}
			set
			{
				if ((this._TenLCT != value))
				{
					this._TenLCT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiHan", DbType="Int")]
		public System.Nullable<int> ThoiHan
		{
			get
			{
				return this._ThoiHan;
			}
			set
			{
				if ((this._ThoiHan != value))
				{
					this._ThoiHan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this._CreateDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateBy", DbType="Int")]
		public System.Nullable<int> CreateBy
		{
			get
			{
				return this._CreateBy;
			}
			set
			{
				if ((this._CreateBy != value))
				{
					this._CreateBy = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifyDate
		{
			get
			{
				return this._ModifyDate;
			}
			set
			{
				if ((this._ModifyDate != value))
				{
					this._ModifyDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifyBy", DbType="Int")]
		public System.Nullable<int> ModifyBy
		{
			get
			{
				return this._ModifyBy;
			}
			set
			{
				if ((this._ModifyBy != value))
				{
					this._ModifyBy = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
