<?xml version="1.0" encoding="utf-8"?><Database Name="KTKS_DonKH" Class="DB_KTKS_DonKHDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=192.168.90.9;Initial Catalog=KTKS_DonKH;Persist Security Info=True;User ID=sa" SettingsObjectName="KTKS_ChungCu.Properties.Settings" SettingsPropertyName="KTKS_DonKHConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TTKhachHang" Member="TTKhachHangs">
    <Type Name="TTKhachHang">
      <Column Name="Khu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Dot" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DanhBo" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CD" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CuLy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MSTLK" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GiaoUoc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="DC1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DC2" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MSKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MSCQ" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GB" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HCSN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SX" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TGDM" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ky" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Nam" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CodeFu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CSCu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CSMoi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgayDSKT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgayDSKN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ChuKyDS" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LNCC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LNCT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LNBuToiThieu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LNSH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LNHCSN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LNSX" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LNDV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CuonGCS" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CuonSTT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GiaBan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ThueGTGT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PhiBVMT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TongCong" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GiaBanBuToiThieu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ThueGTGTBuToiThieu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PhiBVMTBuToiThieu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TongCongBuToiThieu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoPhatHanh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoHoaDon" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgayPhatHanh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Quan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Phuong" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoDHN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MSThue" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TileTieuThu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgayGanDHN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoHo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiChungTu" Member="LoaiChungTus">
    <Type Name="LoaiChungTu">
      <Column Name="MaLCT" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="KyHieuLCT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TenLCT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ThoiHan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChungCu" Member="ChungCus">
    <Type Name="ChungCu">
      <Column Name="DanhBo" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaCT" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Lo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Phong" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaLCT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThoiHan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayHetHan" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="SoNK" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifyDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifyBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>